

CREATE TABLE CANTONES (
    CANTON_ID SERIAL PRIMARY KEY,
    CANTON_NOMBRE VARCHAR(50) NOT NULL,
    PROVINCIA_ID INTEGER NOT NULL,
    CONSTRAINT FK_CANTON_PROVINCIA FOREIGN KEY (PROVINCIA_ID) REFERENCES PROVINCIAS(PROVINCIA_ID)
);


INSERT INTO CANTONES (CANTON_NOMBRE, PROVINCIA_ID) VALUES
('Cuenca', 1),
('Girón', 1),
('Gualaceo', 1),
('Nabón', 1),
('Paute', 1),
('Pucara', 1),
('San Fernando', 1),
('Santa Isabel', 1),
('Sigsig', 1),
('Oña', 1),
('Chordeleg', 1),
('El Pan', 1),
('Sevilla de Oro', 1),
('Guachapala', 1),
('Camilo Ponce Enríquez', 1),
('Guaranda', 2),
('Chillanes', 2),
('Chimbo', 2),
('Echeandía', 2),
('San Miguel', 2),
('Caluma', 2),
('Las Naves', 2),
('Azogues', 3),
('Biblián', 3),
('Cañar', 3),
('La Troncal', 3),
('El Tambo', 3),
('Déleg', 3),
('Suscal', 3),
('Tulcán', 4),
('Bolívar', 4),
('Espejo', 4),
('Mira', 4),
('Montúfar', 4),
('San Pedro de Huaca', 4),
('Latacunga', 5),
('La Maná', 5),
('Pangua', 5),
('Pujili', 5),
('Salcedo', 5),
('Saquisilí', 5),
('Sigchos', 5),
('Riobamba', 6),
('Alausi', 6),
('Colta', 6),
('Chambo', 6),
('Chunchi', 6),
('Guamote', 6),
('Guano', 6),
('Pallatanga', 6),
('Penipe', 6),
('Cumandá', 6),
('Machala', 7),
('Arenillas', 7),
('Atahualpa', 7),
('Balsas', 7),
('Chilla', 7),
('El Guabo', 7),
('Huaquillas', 7),
('Marcabelí', 7),
('Pasaje', 7),
('Piñas', 7),
('Portovelo', 7),
('Santa Rosa', 7),
('Zaruma', 7),
('Las Lajas', 7),
('Esmeraldas', 8),
('Eloy Alfaro', 8),
('Muisne', 8),
('Quinindé', 8),
('San Lorenzo', 8),
('Atacames', 8),
('Rioverde', 8),
('La Concordia', 8),
('Guayaquil', 9),
('Alfredo Baquerizo Moreno (Juján)', 9),
('Balao', 9),
('Balzar', 9),
('Colimes', 9),
('Daule', 9),
('Durán', 9),
('El Empalme', 9),
('El Triunfo', 9),
('Milagro', 9),
('Naranjal', 9),
('Naranjito', 9),
('Palestina', 9),
('Pedro Carbo', 9),
('Samborondón', 9),
('Santa Lucía', 9),
('Salitre (Urbina Jado)', 9),
('San Jacinto de Yaguachi', 9),
('Playas', 9),
('Simón Bolívar', 9),
('Coronel Marcelino Maridueña', 9),
('Lomas de Sargentillo', 9),
('Nobol', 9),
('General Antonio Elizalde', 9),
('Isidro Ayora', 9),
('Ibarra', 10),
('Antonio Ante', 10),
('Cotacachi', 10),
('Otavalo', 10),
('Pimampiro', 10),
('San Miguel de Urcuquí', 10),
('Loja', 11),
('Calvas', 11),
('Catamayo', 11),
('Celica', 11),
('Chaguarpamba', 11),
('Espíndola', 11),
('Gonzanamá', 11),
('Macará', 11),
('Paltas', 11),
('Puyango', 11),
('Saraguro', 11),
('Sozoranga', 11),
('Zapotillo', 11),
('Pindal', 11),
('Quilanga', 11),
('Olmedo', 11),
('Babahoyo', 12),
('Baba', 12),
('Montalvo', 12),
('Puebloviejo', 12),
('Quevedo', 12),
('Urdaneta', 12),
('Ventanas', 12),
('Vínces', 12),
('Palenque', 12),
('Buena Fé', 12),
('Valencia', 12),
('Mocache', 12),
('Quinsaloma', 12),
('Portoviejo', 13),
('Bolívar', 13),
('Chone', 13),
('El Carmen', 13),
('Flavio Alfaro', 13),
('Jipijapa', 13),
('Junín', 13),
('Manta', 13),
('Montecristi', 13),
('Paján', 13),
('Pichincha', 13),
('Rocafuerte', 13),
('Santa Ana', 13),
('Sucre', 13),
('Tosagua', 13),
('24 de Mayo', 13),
('Pedernales', 13),
('Olmedo', 13),
('Puerto López', 13),
('Jama', 13),
('Jaramijó', 13),
('San Vicente', 13),
('Morona', 14),
('Gualaquiza', 14),
('Limón Indanza', 14),
('Palora', 14),
('Santiago', 14),
('Sucúa', 14),
('Huamboya', 14),
('San Juan Bosco', 14),
('Taisha', 14),
('Logroño', 14),
('Pablo Sexto', 14),
('Tiwintza', 14),
('Tena', 15),
('Archidona', 15),
('El Chaco', 15),
('Quijos', 15),
('Carlos Julio Arosemena Tola', 15),
('Pastaza', 16),
('Mera', 16),
('Santa Clara', 16),
('Arajuno', 16),
('Quito', 17),
('Cayambe', 17),
('Mejia', 17),
('Pedro Moncayo', 17),
('Rumiñahui', 17),
('San Miguel de Los Bancos', 17),
('Pedro Vicente Maldonado', 17),
('Puerto Quito', 17),
('Ambato', 18),
('Baños de Agua Santa', 18),
('Cevallos', 18),
('Mocha', 18),
('Patate', 18),
('Quero', 18),
('San Pedro de Pelileo', 18),
('Santiago de Píllaro', 18),
('Tisaleo', 18),
('Zamora', 19),
('Chinchipe', 19),
('Nangaritza', 19),
('Yacuambi', 19),
('Yantzaza (Yanzatza)', 19),
('El Pangui', 19),
('Centinela del Cóndor', 19),
('Palanda', 19),
('Paquisha', 19),
('San Cristóbal', 20),
('Isabela', 20),
('Santa Cruz', 20),
('Lago Agrio', 21),
('Gonzalo Pizarro', 21),
('Putumayo', 21),
('Shushufindi', 21),
('Sucumbíos', 21),
('Cascales', 21),
('Cuyabeno', 21),
('Orellana', 22),
('Aguarico', 22),
('La Joya de Los Sachas', 22),
('Loreto', 22),
('Santo Domingo', 23),
('Santa Elena', 24),
('La Libertad', 24),
('Salinas', 24);