

CREATE TABLE PROVINCIAS (
    PROVINCIA_ID SERIAL PRIMARY KEY,
    PROVINCIA_NOMBRE VARCHAR(35) NOT NULL
);


INSERT INTO PROVINCIAS (PROVINCIA_NOMBRE) VALUES
('AZUAY'),
('BOLÍVAR'),
('CAÑAR'),
('CARCHI'),
('COTOPAXI'),
('CHIMBORAZO'),
('EL ORO'),
('ESMERALDAS'),
('GUAYAS'),
('IMBABURA'),
('LOJA'),
('LOS RÍOS'),
('MANABÍ'),
('MORONA SANTIAGO'),
('NAPO'),
('PASTAZA'),
('PICHINCHA'),
('TUNGURAHUA'),
('ZAMORA CHINCHIPE'),
('GALÁPAGOS'),
('SUCUMBÍOS'),
('ORELLANA'),
('SANTO DOMINGO DE LOS TSÁCHILAS'),
('SANTA ELENA');